- Dockerfile
This will enable to run `make push` without failure, otherwise, docker build fails.
> Run build-dep before building go code

- ISSUE_TEMPLATE
Because we're getting people to build from master, users might be running on different code levels when they report a bug. This change asks reporters what code level they are using so that we can go back to investigate problems using the same code base that they're running from.
> Add commit ID question to issue template

- helm/portieris/values.yaml
Update the chart to point at the most recent build on Docker Hub: https://hub.docker.com/r/ibmcom/portieris/tags/
Fixes https://github.com/IBM/portieris/issues/27
> Update to latest image from Docker Hub

- pkg/controller/notary/controller.go
- pkg/controller/notary/notary_suite_test.go
- pkg/controller/notary/notary_test.go
Added support for applying policy to initContainers as per https://github.com/IBM/portieris/issues/30
The diffs are kind of strange because of the indentations. Only edits are actually on the top of `mutate` function and minor edits.
I had some trouble writing tests for checking the signing with a pod request. I ran into this error:
```
Test Panicked
GetNotaryRepo called before it is stubbed
```
I tried it with `newFakeRequestMultiContainer` and couldn't get it to work too. If someone could help me figure out the testing scaffolding, that would be great. 
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Added support for applying image policy to initContainers

- helm/portieris/values.yaml
0.4.0 is built from master at ff725c44cf2a853843ccf73890c2b17b63609774.
Closes #30
> Update chart to 0.4.0 image

- README.md
Describes how a user can use a different trust server for a repository.
> Document how to use specific trust server

- Makefile
- helpers/image/image_test.go
- helpers/trustmap/trust_server_map.go
... and actually make them run!
> Rewrite image tests to not use ginkgo

- helm/portieris/templates/secret.yaml
This was missed in https://github.com/IBM/portieris/pull/24.
> Consume value for namespace in certs secret

- pkg/controller/notary/controller.go
- pkg/kubernetes/secret.go
- pkg/kubernetes/secret_test.go
- pkg/kubernetes/wrapper.go
- pkg/registry/fakeregistry/fakeregistry.go
- pkg/registry/registry.go
Prevents "no valid IPS" errors when no pullSecret exists where the username is "token".
> Don't assume that the username will be token

- helm/cleanup.sh
The commit updated `cleanup.sh` to make sure RBAC resources will have deleted from Kubernetes cluster.
> Make sure cleanup.sh will delete RBAC resources

- .travis.yml
No longer required: https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517
Fixes https://github.com/IBM/portieris/issues/56
> Remove deprecated sudo flag

- test/framework/namespace.go
following the removal of bluemix references we need to use a different secret in the IBM Kubernetes Service
> use appropriate pull secret in iks

- README.md
Helm have changed the command syntax for installing and deleting charts with 2.16 and 3.x. This means our install docs no longer work.
We don't need --name on the install since we're doing an `upgrade --install`, which always takes release name first, then chart. The delete command is more complicated, and needs `--purge` when using 2.x, and needs to not have it when using 3.x.
Fixes #87
> Remove broken helm options

- helm/portieris/templates/secret.yaml
- helm/portieris/values.yaml
Adding the ability to skip secret creation is useful so that the portieris-certs secret can be managed separately from the helm chart.
> Add the ability to skip secret creation

- helm/portieris/templates/deployment.yaml
- pkg/webhook/webhook.go
Implemented as separate checks in case we want to do something different later on.
https://github.com/IBM/portieris/issues/66
> Add basic liveness and readiness probes

- Dockerfile
- cmd/trust/main.go
- helm/portieris/templates/deployment.yaml
Openshift requires that pods run as non-root - root pods won't start. There's some directories in the container's filesystem that need to be writable to Portieris, so added a little macro to the build that allows it to create the directories it needs with the permissions it needs to run as non-root.
Tested on an IBM Cloud Openshift cluster running Openshift 3.11.
Fixes https://github.com/IBM/portieris/issues/80
> Run as non-root to work on Openshift

- helm/portieris/README.md
- helm/portieris/gencerts
It looks like `yq` was only used to read the `name` from Chart.yaml. But is it likely that `name` will ever change from `portieris`? If not, I think we could make it easier to adopt portieris if we remove this dependency and just hard-code the service name.
My specific use-case is that I have to use a restricted bastion host to deploy my helm charts, and that bastion host doesn't have `yq` installed on it.
Feel free to close this PR if there is a situation where hardcoding `SERVICE_NAME=portieris` would cause problems. I may be missing the big-picture. 👍
> Remove dependency on yq

- helpers/oauth/oauth.go
This commit adds support for using the custom ca certificate
at "/etc/certs/ca.pem", similar to what is done inside of "notary.go"
Closes-bug: https://github.com/IBM/portieris/issues/99
Signed-off-by: Joseph Richard <joseph.richard@windriver.com>
> Use custom ca cert in oauth helper

- README.md
- helm/portieris/templates/clusterrole.yaml
- helm/portieris/templates/clusterrolebinding.yaml
- helm/portieris/templates/crd-creation/configmap.yaml
- helm/portieris/templates/crd-creation/create-crds.yaml
- helm/portieris/templates/crd-creation/delete-crds.yaml
- helm/portieris/templates/deployment.yaml
- helm/portieris/templates/securitycontextconstraint.yaml
- helm/portieris/templates/serviceaccount.yaml
- helm/portieris/values.yaml
This enhancement adds support for OpenShift and Helm3.  To support Helm3 adjustments were made to hook annotations so that resources are applied in proper order during creation and deletion.  In addition, in order to successfully install the image/cluster image policies, the `patch` verb was added in the cluster role resource for apiGroup `securityenforcement.admission.cloud.ibm.com`.
To support OpenShift a security context contraint was added for the `portieris` service account.  This `scc` must be in place prior to instantiating the deployment, so the helm `pre-install` hook annotation was utilized.
Closes: https://github.com/IBM/portieris/issues/127
Closes: https://github.com/IBM/portieris/issues/124
> Support Helm3 and OpenShift

- CHANGELOG.md
- helm/portieris/templates/service.yaml
The Portieris server is a HTTPS one, but we were saying it was HTTP in the service. This incorrect protocol reportedly breaks Istio's proxying of TLS requests.
> Set service protocol appropriately

- helm/portieris/README.md
The default behavior is to --purge and if you want to retain your history you now need to explicitly use, when deleting/uninstalling, --keep-history
> --purge has been removed from helm 3

- POLICIES.md
- helm/portieris/README.md
In setting this up using the latest feature of look-aside signatures, last week, I spent a few hours trying to understand how the secret should have been created - particularly the name of the key it was looking for. Naming it anything other than 'key' would not work. By default, i believe it picks up the basename of the file. Either way, adding an example for clarity.
Lastly, when I was trying to figure out how to configure for look-aside, I could not find anything relevant to the statement mentioning 'KeyType' and removed it. The literal word 'KeyType' does not show anywhere in the doc and it was a little confusing to read.
> Adding creating secret example

- README.md
- helm/cleanup.sh
Since we're using helm 3, allow it to create the namespace for us. adjust the documentation, on deleting, as helm delete will not find the release if not in the 'default' namespace. Additionally, notify user that any created namespaces are not cleaned up on a helm delete.
> adjust helm usage - optimize/adjust docs

- pkg/notary/notary.go
- pkg/registry/registry.go
- pkg/verifier/trust/verifier.go
Allow access to anonymous notary servers (those without authentication turned on). I found this to be necessary when running my own notary server for storing signatures of images in ECR.
I did this by suffixing username "" password "" to the end of the real credentials array, and having methods that hit oauth and compose authentication headers be aware of this.
Opening in draft to get feedback on the approach while I'm continuing to test.
> Allow anonymous notary access

- CHANGELOG.md
- README.md
- cmd/trust/main.go
- helm/portieris/gencerts
- helm/portieris/templates/admission-webhooks/webhooks.yaml
- helm/portieris/templates/secret.yaml
- helm/portieris/values.yaml
Rename portieris certs from serverCert.pem and serverKey.pem to tls.crt
and tls.key, following the naming conventions used by cert-manager.
In combination with SkipSecretCreation=true, this allows using
cert-manager to generate portieris certs.
https://github.com/IBM/portieris/issues/59
Signed-off-by: Joseph Richard <jrichard@josephrichard.com>
> Use cert-manager naming convention for portieris

- README.md
- helm/portieris/templates/namespace.yaml
- helm/portieris/templates/webhooks.yaml
- helm/portieris/values.yaml
This prevents the webhook from being called for the Portieris install namespace, which means that Portieris can recover itself in the case of cluster failure.
Without this an approval from the Portieris webhook is needed to okay scaling itself up. This means that with no pods available, the webhook can't approve the recovery of any Portieris pods, and so the cluster deadlocks.
This change gives the Portieris chart ownership of the portieris install namespace, and labels it in such a way that we can filter for it in the webhook config.
It's configured as an opt out, rather than Istio's which is an opt in. All namespaces without the label are fair game.
By adding the namespace into the chart, it'll be deleted by Helm when the chart gets removed. And adding the label selector means that the …
> Use a namespace selector for admission webhook

- helm/portieris/gencerts
Previous version failed in automation if the working directory contained spaces in any directory names.
> Make gencerts safe for directories containing spaces

- helm/portieris/templates/namespace.yaml
Higher in priority than serviceaccount
Fixes https://github.com/IBM/portieris/issues/181
> Assign a weighting to namespace pre-install

- CHANGELOG.md
- Makefile
- helm/portieris/Chart.yaml
- helm/portieris/values.yaml
- test/e2e/notary.ibm.clusterimagepolicy_test.go
- test/e2e/notary.ibm.imagepolicy_test.go
- test/e2e/simple.imagePolicy_test.go
- test/e2e/wildcard.generic_test.go
and minor fixes to e2e tests to accommodate previous rename of default cluster image policy.
> Prepare for 0.8.1 release

- CHANGELOG.md
Make it clearer that 0.8.1 drops support for Helm 2
> Clarify Helm 3 items in 0.8.1 release

- pkg/controller/multi/controller.go
- pkg/controller/multi/controller_test.go
Uses a global decisions map for image decisions across multiple containers, and a local denials map returned from the getPatchesFromContainers and appends to the global decisions map.
Then outputs the image:tag keys of the decisions map in the Allow and Deny decision branches
> #216 fixes the lack of logging seen in the portieris output for decisions

- cmd/portieris/main.go
- helpers/kube/kube.go
This flag provides the ability to specify a kubeconfig file location
to use via the command line for an out-of-cluster kube client configuration.
> Add --kubeconfig command line flag option

- cmd/portieris/main.go
- helpers/kube/kube.go
The same logic is used to retrieve the kube client config in the `GetKubeClient` and `GetPolicyClient` methods.  This change puts that logic into a common method in which the others can take advantage of.
> Make common method for retrieving kube client config

- helpers/kube/kube.go
Upon testing out these latest changes, I found the following nil pointer error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ee3ba]
goroutine 1 [running]:
github.com/IBM/portieris/pkg/apis/securityenforcement/client/clientset/versioned.NewForConfig(0x0, 0x12a43df, 0xc0000f8200, 0xc0001b42c0)
/go/src/github.com/IBM/portieris/pkg/apis/securityenforcement/client/clientset/versioned/clientset.go:59 +0x3a
github.com/IBM/portieris/helpers/kube.GetPolicyClient(0xc0000f8200, 0xc0003d0f40)
/go/src/github.com/IBM/portieris/helpers/kube/kube.go:83 +0x2e
main.main()
/go/src/github.com/IBM/portieris/cmd/portieris/main.go:69 +0x528
```
> nil pointer bug fix

- helm/portieris/templates/clusterrole.yaml
- helm/portieris/templates/clusterrolebinding.yaml
- helm/portieris/templates/serviceaccount.yaml
The Portieris Helm chart doesn't always properly clean up installed resources - this is because we override the default Helm object creation logic with Helm preinstall hooks, and [as the Helm documentation states](https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases), resources annotated with hooks are considered unmanaged by Helm and will not be removed on chart uninstall.
This annoyed me enough times to cause me to investigate, and I realized that we don't actually _need_ to muck with Helm's installation ordering for most cases - it already does the right thing, which is why the use of Helm hooks is generally discouraged in most cases.
The only time we need to override the default Helm behavior (and break chart resource cleanup) is if …
> Explicit Helm install ordering only required on OpenShift, and breaks cleanup elsewhere

- helm/portieris/templates/policies.yaml
- helm/portieris/values.yaml
Since we expect people to customize the default ClusterImagePolicy as an allowlist, it makes sense for it to be a Helm variable set in `values.yaml`, so that this value can be injected at installtime via the CLI, or overridden from a parent Helm chart.
> Make the ClusterImagePolicy a Helm variable, so it can easily be overridden by users

- go.sum
- pkg/kubernetes/podspec.go
- pkg/kubernetes/podspec_test.go
After the change we would only return `ErrObjectHasParents` in the case the parent is of a supported kind.
Currently if a resource has an owner of any kind we do not admit as we expect the admission to happen at the owner level.
In the case where the owner is not a supported kind e.g. a CRD this leads to the resource being created with no admission occurring anywhere in the chain.
fixes: #246
> Add additional validation to owner check

- Dockerfile
- Makefile
- cmd/portieris/main.go
- helpers/kube/kube.go
- helpers/oauth/oauth.go
- helpers/useragent/useragent.go
- helpers/useragent/useragent_test.go
- internal/info/info.go
- pkg/notary/notary.go
- pkg/verifier/simple/imagePolicy.go
> Set all the User-Agents & include the version

- helm/portieris/crds/crds.yaml
- pkg/apis/portieris.cloud.ibm.com/v1/types.go
- pkg/verifier/simple/policy.go
- test/e2e/policy.generic_test.go
- test/e2e/simple.imagePolicy_test.go
- test/e2e/testdata/imagepolicy/simple-signedby1-keysecret-namespace-override.yaml
- test/e2e/utils/imagepolicy.go
- test/e2e/vulnerability.imagePolicy_test.go
- test/e2e/wildcard.generic_test.go
This gives the ability to specify a namespace to look for the secret
specified in the `keySecret` field that will override the default behavior of just
looking in the namespace of the image being admitted.
> Add keySecretNamespace policy option

- .pre-commit-config.yaml
- .secrets.baseline
Signed-off-by: James Hart <jhart@uk.ibm.com>
Secrets marked as false positives:
- In POLICIES.md - they are strings like `keySecret: my-pubkey` , which are not secrets.
- In e2e test framework, there are some public keys, which are permitted (as they are public).
> Add secrets baseline and pre-commit config

- helm/portieris/templates/deployment.yaml
- helm/portieris/values.yaml
- add useHostNetwork value to the values.yaml, default to false
- use the value in deployment.yaml to set hostNetwork: true for the deployment
helm template meow ./portieris/ --set useHostNetwork=true
```
spec:
serviceAccountName: portieris
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
containers:
- name: portieris
image: "icr.io/portieris/portieris:v0.10.1"
imagePullPolicy: Always
ports:
```
if useHostNetwork=false or just not --set
```
spec:
serviceAccountName: portieris
containers:
- name: portieris
image: "icr.io/portieris/portieris:v0.10.1"
imagePullPolicy: Always
ports:
```
> added hostnetwork option to values and deployment.yaml

- go.mod
- go.sum
- helm/portieris/templates/webhooks.yaml
- pkg/controller/fakecontroller/controller.go
- pkg/controller/interface.go
- pkg/controller/multi/controller.go
- pkg/controller/multi/controller_test.go
- pkg/controller/multi/notary_suite_test.go
- pkg/controller/multi/notary_test.go
- pkg/kubernetes/podspec.go
- pkg/kubernetes/podspec_test.go
- pkg/kubernetes/wrapper.go
- pkg/webhook/responder.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
Moving to the v1 webhook not so simple, obviously requires that the response is of the v1 type.
issue: https://github.com/IBM/portieris/issues/215
> v1 hook should return a v1 result

- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
the Kind/ApiVersion metadata is required in the response (new requirement in v1) this copies it from the request
issue: https://github.com/IBM/portieris/issues/215
> copy typemeta from request to response

- CHANGELOG.md
- helm/portieris/templates/clusterrolebinding.yaml
clusterrolebinding is the last deprecated resource still in use
fixes: https://github.com/IBM/portieris/issues/215
> update deprecated resource

- helm/portieris/templates/deployment.yaml
- helm/portieris/values.yaml
Resolves #323 
The following change is intended to allow an administrator more flexibility when configuring a Portieris deployment. It is common for security tools to demand certain `podAnnotations` are set in order to reach a specified level of compliance or a service mesh to use `podAnnotations` to change its configuration. 
The change will allow users to overwrite the metric annotations if the user provides matching keys. Introducing `$metric_annotations` and `mergeOverwrite` produces a more predictable outcome, and ensures the user cannot duplicate annotations. If no pod annotations are given the `prometheus.io/port: "8080"` and `prometheus.io/scrape: "true"` will be the default
- Add ability to optionally set `podAnnotations` on the deployment resource
`values.yaml`
```yaml …
```
> add ability to set podAnnotations on deployment resource

- pkg/apis/portieris.cloud.ibm.com/v1/types.go
Apparently there is no "inline" struct tag that encoding/json recognizes. The Kubernetes repo uses it all over the place, but it does not actually do anything.
There's an open issue to add the feature in, however it's not been closed yet.
See https://github.com/golang/go/issues/6213
Issue Link: https://github.com/IBM/portieris/issues/276
Signed off by: Adrian Osadcenco adrian.osadcenco@ibm.com
Also see source code for the `encoding/json` library, there is no mention of an `inline` struct tag.
[https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L78-L134](url)
> Remove invalid `inline` struct tag

- helm/portieris/templates/secret.yaml
Legacy API versions have been removed from cert-manager since the v1.6 release
Including v1alph2, v1alph3, and v1beta1
Learn more
- https://cert-manager.io/docs/release-notes/release-notes-1.6/
This has been tested in our v1.21 IKS cluster
> fix: use cert-manager v1 APIs

- helpers/image/image_test.go
- pkg/verifier/trust/verifier.go
Handle "Forbidden/403" correctly on trust where multiple secrets are available. 
Tested in e2e tests.
> Forbidden handing

- README.md
- helm/portieris/README.md
- helm/portieris/templates/webhooks.yaml
- helm/portieris/values.yaml
The values file allows you to define `tlsCert` and `tlsKey` when `UseGeneratedCerts` is set to true. But there is no way to define the ca cert used by the webhooks when you aren't using cert-manager, it only allows you to define it from the generated ca.crt file, which seems to defeat the purpose. This PR allows this CA cert to be defined from values.
> Make CA cert definable

- RELEASE-HOWTO.md
Intention is to make it possible to consume a patch version containing a vulnerability fix without needing to review the Helm chart first.
> Require minor version bump for Helm chart changes

- CHANGELOG.md
- Change header levels to H2 for version names to appear as under the "Change Log" title in the header hierarchy
- Change release dates from headings to text to avoid duplicates
- Add release dates where they were missing
- Add release text for v0.12.5
- Update v-next template to use new release date format
- Fix malformed markdown in link to issue in v0.13.0 release notes
- Added hashes to issue numbers and PR annotations where missing for consistency with earlier releases
> Reformat CHANGELOG for consistency

- helm/portieris/templates/secret.yaml
- helm/portieris/values.yaml
Currently, always a new issuer is created for portieris. This PR exposes overrides so that one can configure an already existing issuer to be used.
This is especially important for rotation use-cases. Currently, since self-signed issuer is used on each rotation the certificate is issued by a different issuer. This means that the old certificate is automatically invalid since the issuer is different. Portieris deployment needs to be restarted in order to pick up the new cert.
If we manage to use an existing cert-manager issuer, one can configure a stable one that will be used for portieris certificates. This way, when a certificate is rotated, the issuer will be the same and the cert will be valid for a few days more until it actually expires - enough time for redeployment to happen and …
> Allow using external cert manager issuer

- helm/portieris/templates/deployment.yaml
- helm/portieris/values.yaml
Hi,
Helm upgrade doesn’t restart the deployment, if the deployment manifest doesn’t get changed. There is a solution for that https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments.
For that case additional annotations should be added to the deployment itself.
> feat: add deployemntAnnotations to the helm chart 

- helm/portieris/templates/pdb.yaml
Currently, we are experiencing some issues with the `semverCompare` logic inside the PDB of the Helm chart as it cannot handle the Kubernetes GitVersion for clusters on GKE. 
The output of running `kubectl version`:
`.Capabilities.KubeVersion.GitVersion` looks at the GitVersion of the Kubernetes cluster; in our case that is a GKE cluster which has the GitVersion of `GitVersion:"v1.24.16-gke.500"` (retrieved by running `kubectl version`). The issue stems from the `-gke.500` which according to the [Helm docs](https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions) is considered as a pre-release.
The solution provided seems to work both with GitVersion without a pre-release, such as `1.20.0` or `1.24.0`, and GitVersions with a pre-release, such as …
> Change semverCompare in PDB

- helm/portieris/templates/webhooks.yaml
- helm/portieris/values.yaml
Hi there,
part of the admission control [best practises is to skip kube-system namespace](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace). This PR would add an option for a user to create a matchExpression which suits their case.
Hope that suits well,
Johnny
> feat: add namespace selector for skipping admission

- helm/portieris/values.yaml
The key failure-domain.beta.kubernetes.io is deprecated and the replacement is topology.kubernetes.io.
https://kubernetes.io/docs/reference/labels-annotations-taints/
> Replace failure-domain.beta.kubernetes.io with topology.kubernetes.io

- .secrets.baseline
- CHANGELOG.md
- Makefile
- go.mod
- go.sum
- helm/portieris/Chart.yaml
- helm/portieris/values.yaml
- scripts/env.sh
- test/e2e/testdata/deployment/dockerhub-nginx-unsigned.yaml
Bump golang.org/x/net for CVE-2023-45288
Bump github.com/docker/docker for CVE-2024-29018
> Prepare v0.13.14

- CHANGELOG.md
- Makefile
- helm/portieris/Chart.yaml
- helm/portieris/values.yaml
- scripts/env.sh
> Prepare 0.13.15 release

- .secrets.baseline
- CHANGELOG.md
- Makefile
- helm/portieris/Chart.yaml
- helm/portieris/values.yaml
- scripts/env.sh
Remediates CVE-2024-9355 in golang
A rebuild should fix this as we are using `registry.access.redhat.com/ubi8/go-toolset:1.21.13` and that says it has `golang-1.21.13-3.module+el8.10.0+22345+acdd8d0e.x86_64` which is what the vuln issue asked for:
`Corrective action: Upgrade golang to >= 0:1.21.13-3.module+el8.10.0+22345+acdd8d0e`
Reference: https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?container-tabs=packages
Locally tested as per [the runbook](https://pages.github.ibm.com/alchemy-registry/operational-docs/runbooks/cr/release_portieris/#action-to-take---test) and all was successfull.
> Prep v0.13.20

- .secrets.baseline
- CHANGELOG.md
@tim-gp already did most of the legwork for creating this release in #479. This just needs updating the release date.
> Prep release v0.13.24

- .nancy-ignore
- CHANGELOG.md
- Makefile
- helm/portieris/Chart.yaml
- helm/portieris/values.yaml
v0.13.25 to release a vuln fix to go-jose (plus associated dependency updates)
A nancy-ignore is added for a separate vuln that cannot be fixed until refactoring the dockerbuild to use a higher golang version than RedHat currently provide
> Prep release v0.13.25
