README.md

https://github.com/IBM/portieris/issues/45

Document generating new certs

---

pkg/notary/notary.go

This addresses #53 (and the description of the problem can be found there)

server and image are not needed

---

README.md

update links to ICCR and IBM Cloud docs

---

helm/portieris/README.md
helm/portieris/gencerts

Use mikefarah yq

---

pkg/controller/multi/controller.go
pkg/controller/multi/notary_test.go

Fixes https://github.com/IBM/portieris/issues/98

Wrap policy errors to help explain what happened

---

test/e2e/testdata/imagepolicy/simple-accept-anything.yaml

incorrect name

---

scripts/copyright-check.sh
scripts/copyright.sh

make copyright tools do copyright

---

pkg/controller/multi/controller.go
pkg/controller/multi/notary_test.go

To close: https://github.com/IBM/portieris/issues/90

no tag in mutated image

---

README.md
helm/cleanup.sh
helm/portieris/gencerts
helm/portieris/templates/admission-webhooks/delete-admission-webhooks.yaml
helm/portieris/templates/clusterrole.yaml
helm/portieris/templates/clusterrolebinding.yaml
helm/portieris/templates/crd-creation/delete-crds.yaml
helm/portieris/values.yaml

https://github.com/IBM/portieris/issues/117
also fix clean install and doc for same since helm 3

change default namespace and fix hook-weight

---

helm/portieris/templates/default/policies.yaml

update installed policies in line with https://github.com/IBM/portieris/issues/94
fix https://github.com/IBM/portieris/issues/95

Revise default policies

---

Makefile
RELEASE-HOWTO.md
go.mod
go.sum
helm/portieris/Chart.yaml
helm/portieris/values.yaml
pkg/controller/multi/controller.go
scripts/copyright-check.sh

Release proc

---

Makefile
README.md
RELEASE-HOWTO.md
helm/portieris/Chart.yaml
helm/portieris/values.yaml

cant use + in a tag

---

.travis.yml
CHANGELOG.md
Makefile
pkg/controller/multi/notary_test.go
pkg/registry/fakeregistry/fakeregistry.go

unclear why PR checker passed
looks like make test exits 0 if fails

fix unit test after merge

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

start work on next release

---

go.mod
go.sum
pkg/kubernetes/secret.go
pkg/kubernetes/secret_test.go

For: https://github.com/IBM/portieris/issues/174

Use registry credentials from encoded auth field if set

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

Reset version tags for vNext release

---

helpers/kube/kube.go

The changes here will give users the ability to install Portieris in an "out-of-cluster" configuration.  It uses the KUBECONFIG env var to specify the kubeconfig for the cluster Portieris needs to manage.  The in-cluster configuration that exists today will still function like normal when there is no KUBECONFIG env var set.
If choosing to run Portieris in an out-of-cluster configuration, these are the required changes/steps you would need to take:
- ensure KUBECONFIG env var is defined in Portieris runtime and it points to a valid kubeconfig file location
- ensure the tls certs are available at `/etc/certs` in new runtime location
- expose Portieris such that it is reachable from the kubernetes apiserver
- change the MutatingWebhookConfiguration to point to your new Portieris URL
Resolves …

Provide option to run out of cluster

---

helpers/credential/credential.go
pkg/controller/multi/controller.go
pkg/verifier/simple/imagePolicy.go
pkg/verifier/simple/imagePolicy_test.go
pkg/verifier/trust/verifier.go

Use a struct instead of a `[][]string`

Make it clear what's a username and what's a password

---

go.mod
go.sum
pkg/controller/multi/controller.go
pkg/controller/multi/controller_test.go
pkg/verifier/simple/verifier.go
pkg/webhook/responder.go

This improves readability and testability
Also add unit testing to new function in table test so that extending the function will be easier with tdd

Avoid loop in loop by refactoring inner loop to new function

---

CHANGELOG.md
Makefile
go.mod
go.sum
helm/portieris/Chart.yaml
helm/portieris/values.yaml

Values, labels, changelog go mod etc.

Prep for v0.8.2

---

helm/portieris/gencerts

update gencert to add SAN

---

test/framework/namespace.go

This change causes the tests to fail due to #209 
Specifically, the following tests will fail:
```text
TestSimple_ImagePolicyRepositories_AllowAllDenyAll/Allow_all_images
TestSimple_ImagePolicyRepositories_Basic/Allow_images_signed_by_the_correct_single_simple_signer
TestSimple_ImagePolicyRepositories_Basic/Allow_images_signed_the_correct_multiple_simple_signers
```
These fail because simple signing will fail on the first matching imagePullSecret it finds (the bad one), rather than continuing to try the next matching pull secret.
Signed-off-by: James Hart <jhart@uk.ibm.com>

Enhance e2e tests to introduce bad pull secrets

---

pkg/verifier/simple/imagePolicy.go

Fixes #209 
This also makes the tests pass again after the recreate introduced in #210 
Some comments on this fix:
- I believe the previous switch statement (to move onto the next pull secret depending on the error) was in the wrong place and was dead code. Hence it has been deleted.
- Unfortunately, it's not possible to use a similar switch statement in the correct place - because the error returned from the `containters/image` library is not typed. Not is it wrapped in a way that would enable use of `errors.Is()`.
- After discussing with colleagues, we believe the best approach is just to try the next pull secret on any error, but to ensure there's sufficient logging to diagnose the problem.
- The unit tests do not cover these code paths, presumably due to the difficulty in …

Move pull secret iteration logic to correct place

---

.travis.yml

remove docker/bundler(ruby)

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

prepare 0.9.2

---

.github/workflows/go-portieris.yaml
.travis.yml

- converted travis.yaml to github action
- added to run on self-hosted runners
Signed-off-by: JJ Asghar <jjasghar@gmail.com>

Added a github action workflow

---

helpers/kube/kube.go
pkg/controller/multi/controller.go
pkg/controller/multi/controller_test.go

fixes: https://github.com/IBM/portieris/issues/227

allow deployments with blank/placeholder image

---

CHANGELOG.md
README.md
RELEASE-HOWTO.md

update RELEASE-HOWTO.md and install instructions

---

CHANGELOG.md
POLICIES.md
go.mod
go.sum
pkg/apis/securityenforcement/client/clientset/versioned/clientset.go
pkg/apis/securityenforcement/v1beta1/types.go
pkg/verifier/simple/policy.go
pkg/verifier/simple/policy_test.go
test/e2e/simple.imagePolicy_test.go
test/e2e/testdata/deployment/global-nginx-remapped.yaml
test/e2e/testdata/imagepolicy/simple-remap.yaml

reflect the remapIdentity support recently added to https://github.com/containers/image
resolves: https://github.com/IBM/portieris/issues/92

support remapIdentity simple policies

---

CHANGELOG.md
helm/portieris/values.yaml

part of: https://github.com/IBM/portieris/issues/205

switch registries

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

prepare release v0.9.5

---

.github/workflows/go-portieris.yaml
pkg/verifier/simple/imagePolicy.go
pkg/verifier/simple/imagePolicy_test.go
scripts/copyright-check.sh

try setting TERM=ansi to get colour and no error
make copyright-check.sh fail the tests
with some wrong copyrights to test it

copyright fails test, terminal

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

++ version and tidy up changelog

prepare for next version

---

scripts/copyright.sh

If there is currenlty one year we should append the current year.

Fix copyright statements

---

.secrets.baseline

Signed-off-by: James Hart <jhart@uk.ibm.com>

Update .secrets.baseline from latest tool

---

CHANGELOG.md
Dockerfile
Makefile
go.mod
go.sum
helm/portieris/Chart.yaml
helm/portieris/values.yaml
test/e2e/notary.ibm.imagepolicy_test.go

prepare to release 0.10.2

---

README.md
helm/portieris/README.md

correct links to RBAC
fixes: https://github.com/IBM/portieris/issues/329

replace broken links

---

pkg/apis/portieris.cloud.ibm.com/v1/types.go

issue: https://github.com/IBM/portieris/issues/276

omitempty typo

---

pkg/webhook/webhook.go

Force TLS version 1.2 to resolve security scan finding

Remove TLS 1.0 support

---

POLICIES.md

https://github.ibm.com/alchemy-registry/registry-build-squad/issues/4306

add customizing policies

---

pkg/verifier/simple/imagePolicy.go

adds error handling to code in the `verifyAttempt` method.
Issue Link: #273

handle errors in verifier

---

helm/portieris/templates/deployment.yaml
helm/portieris/values.yaml

https://github.com/IBM/portieris/issues/78

Add priorityClass to the portieris deployment

---

.secrets.baseline
POLICIES.md

In noticed that there are still some refs to old apigroup and api versions

Update POLICY.md with current apigroup, versions

---

CHANGELOG.md
Dockerfile
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

Prep v0.12.2

---

go.mod
go.sum
test/e2e/utils/clusterimagepolicy.go
test/e2e/utils/imagepolicy.go
test/framework/utils.go

Signed-off-by: James Hart <jhart@uk.ibm.com>
Fixes https://github.com/IBM/portieris/issues/366

Remove satori/go.uuid from project

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

Bump the version for a image rebuild. 

prepare v0.12.4

---

helm/portieris/gencerts

sha256 sign cert

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

Pull CHANGELOG.md updates from v0.12 and target v0.13
+ fix the Chart.yaml

Target v0.13

---

POLICIES.md

https://github.ibm.com/alchemy-registry/registry-build-squad/issues/4869

XPath notation

---

CHANGELOG.md

CHANGELOG the major thing in this release

---

CHANGELOG.md
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

bump versions for v0.12.6

---

CHANGELOG.md

release today

---

CHANGELOG.md

changelog for v0.13.1

---

files.txt

We are installing go from go-toolset so need to make sure we are tracking vulns on that package

We should be tracking the golang RH package

---

.gitignore
CHANGELOG.md
Makefile
helpers/oauth/oauth.go
pkg/controller/multi/enforcer_test.go
pkg/verifier/simple/policy_test.go
scripts/copyright-check.sh
scripts/copyright.sh
scripts/env.sh
scripts/install-on-docker
scripts/uninstall-on-docker
test/e2e/utils/cronjob.go
test/framework/cronjob.go

A few things going on here:
1. fix e2e tests for compatibility with K1.25 (cronjob type)
2. some scripts to help run tests 
3. Makefile updates to make fmt be more useful and tests to be safer

fmt, testing fixes and helpers

---

.secrets.baseline

.secrets.baseline missing env.sh

---

scripts/makeKeySecret.sh

Supplement documentation with a script to create a key secret.

prescription for a simple key secret

---

CHANGELOG.md
Dockerfile

remediate vulnerabilities CVE-2023-44487 CVE-2023-29406 CVE-2023-39325

---

CHANGELOG.md

set the release date to today!

set release date

---

.github/workflows/go-portieris.yaml
CHANGELOG.md
Dockerfile
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml
scripts/env.sh

prepare release

---

helm/portieris/values.yaml

resolves #477 
thanks for the issue

Fix typo in "deploymentAnnotations"

---

.pre-commit-config.yaml
.secrets.baseline
CHANGELOG.md
Makefile
go.mod
go.sum
helm/portieris/Chart.yaml
helm/portieris/values.yaml

Chore(deps): remediate CVE-2024-45339

---

.secrets.baseline
CHANGELOG.md
Dockerfile
Makefile
helm/portieris/Chart.yaml
helm/portieris/values.yaml

- **Prep release v0.13.30**
- **Updates secrets.baseline and charts**

Prep release v0.13.30
